MyEureka:
  serverUrl: http://127.0.0.1:8080/eureka/

server:
  port: 8762


eureka:
  client:
    serviceUrl:
        defaultZone: ${MyEureka.serverUrl} #注册中心地址
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  instance:
    status-page-url: http://localhost:${server.port}
    prefer-ip-address: true      #使用ip地址的形式定义注册中心
spring:
  application:
    name: serviceTest2 #服务名





